name = "Frank Allenby"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "I am no bio"
company = "allen.by"
location = "South Africa"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"
